### ISSUE TITLE
What is the real name of the game?

### ISSUE THREAD

**Issue by vipranarayan14** [Antolius/Sage#11]
The game is amazing!  Very entertaining! Thank you!

May I know the name of the original game? So that I can find an equivalent version of this game for Android? 
I couldn't find it in the README nor on the linked Reddit page.

**Comment by Antolius** [comment]
Hi @vipranarayan14, I'm glad you like Sage!

The original code breaking game that Sage is based on is called [Bulls and Cows](https://en.wikipedia.org/wiki/Bulls_and_Cows). There are multiple spinoffs of that original concept, including [a board game series](https://en.wikipedia.org/wiki/Mastermind_(board_game)), or a more recent [web-based word puzzle game Wordle](https://en.wikipedia.org/wiki/Wordle), implementation of which can also [be found in elementary's AppCenter](https://appcenter.elementary.io/com.github.avojak.warble/)!

As for Android apps, [search for "code breaking games" on Google Play](https://play.google.com/store/search?q=code%20breaking%20game&c=apps) includes some pretty familiar looking results. Even F-Droid store [has a result for this search query](https://search.f-droid.org/?q=code+breaking+game&lang=en). I don't have personal experience with these apps, so I can't recommend one over the others.

**Comment by vipranarayan14** [comment]
Ah, yes! I felt that the game was similar to the Bulls and Cows game. But with colours, it is more fun. Thank you, @Antolius!

Also thanks for taking the extra effort for giving the links to similar games.
